osx_image: xcode8.3
language: objective-c

script:
  - xcodebuild test -scheme OptionalExtensions-Mac | xcpretty -c
  - xcodebuild test -scheme OptionalExtensions-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme OptionalExtensions-tvOS -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme OptionalExtensions-watchOS -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty -c

  after_success:
  - bash <(curl -s https://codecov.io/bash)